name: Upload platformio library

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy_engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: void step
        run: echo '123'
