name: Upload platformio library

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  check_valid_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: No upload if tag is a release candidate
        if: contains(github.event.ref, '-rc.')
        run: |
          echo "Stop job: release candidate tag is ignored"
          exit 1
  nothing_to_do_ls:
    needs: check_valid_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: do xxx
        run: |
          ls
          echo 'bla bla bla'
