name: Upload platformio library

on:
  push:
    tags:
      - "*"
    tags-ignore:
      - rc_*
  workflow_dispatch:

jobs:
  nothing_to_do_ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LS
        run: |
          ls
